version: '3.9'

services:
  giropops-senhas:
    build: .
    ports:
      - "5000:5000"
    networks:
      - giropops-senhas
    environment:
      - REDIS_HOST=redis
    volumes:
      - natalia:/granato
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.25'
          memory: 128M
        limits:
          cpus: '0.50'
          memory: 256M

  redis:
    image: redis
    networks:
      - giropops-senhas

networks:
  giropops-senhas:
    driver: bridge

volumes:
  natalia: